
package com.pets.dog.soap.web.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This method will help to load dog information
 * 		
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DogSoapWebService", targetNamespace = "http://service.web.soap.dog.pets.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DogSoapWebService {


    /**
     * 
     * @param pdog
     * @return
     *     returns com.pets.dog.soap.web.service.StringResponse
     * @throws SoapDogFault
     */
    @WebMethod(action = "http://service.web.soap.dog.pets.com/addDog")
    @WebResult(name = "stringResponse", targetNamespace = "http://service.web.soap.dog.pets.com/", partName = "rstring")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public StringResponse addDog(
        @WebParam(name = "uploadDog", targetNamespace = "http://service.web.soap.dog.pets.com/", partName = "pdog")
        PDog pdog)
        throws SoapDogFault
    ;

    /**
     * 
     * @param delete
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://service.web.soap.dog.pets.com/deleteDog")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteDog", targetNamespace = "http://service.web.soap.dog.pets.com/", className = "com.pets.dog.soap.web.service.DeleteDog")
    @ResponseWrapper(localName = "stringResponse", targetNamespace = "http://service.web.soap.dog.pets.com/", className = "com.pets.dog.soap.web.service.StringResponse")
    public String deleteDog(
        @WebParam(name = "delete", targetNamespace = "")
        String delete);

    /**
     * 
     * @param update
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://service.web.soap.dog.pets.com/updateDog")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateDog", targetNamespace = "http://service.web.soap.dog.pets.com/", className = "com.pets.dog.soap.web.service.UpdateDog")
    @ResponseWrapper(localName = "stringResponse", targetNamespace = "http://service.web.soap.dog.pets.com/", className = "com.pets.dog.soap.web.service.StringResponse")
    public String updateDog(
        @WebParam(name = "update", targetNamespace = "")
        String update);

}
