
package com.pets.dog.topdown.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;

import com.pets.dog.service.DogServiceImpl;
import com.pets.dog.web.controller.DogController;


/**
 * This method will help to load dog information
 * 		
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DogSoapWebService", targetNamespace = "http://service.web.soap.dog.pets.com/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DogSoapWebService {
	

	


    /**
     * 
     * @param pdog
     * @return
     *     returns com.pets.dog.topdown.soap.StringResponse
     * @throws SoapDogFault
     */
    @WebMethod(action = "http://service.web.soap.dog.pets.com/addDog")
    @WebResult(name = "stringResponse", targetNamespace = "http://service.web.soap.dog.pets.com/", partName = "rstring")
    public StringResponse addDog(
        @WebParam(name = "uploadDog", targetNamespace = "http://service.web.soap.dog.pets.com/", partName = "pdog")
        PDog pdog)
        throws SoapDogFault
    ;

    /**
     * 
     * @param findAllDogsRequestParam
     * @return
     *     returns com.pets.dog.topdown.soap.FindAllDogOutput
     */
    @WebMethod(action = "http://service.web.soap.dog.pets.com/findAllDogs")
    @WebResult(name = "findAllDogsOutputParam", targetNamespace = "http://service.web.soap.dog.pets.com/", partName = "findAllDogsResponseParam")
    public FindAllDogOutput findAllDogs(
        @WebParam(name = "findAllDogsInputParam", targetNamespace = "http://service.web.soap.dog.pets.com/", partName = "findAllDogsRequestParam")
        FindDogsInput findAllDogsRequestParam);

    /**
     * 
     * @param findDogByIdRequestParam
     * @return
     *     returns com.pets.dog.topdown.soap.DogForm
     */
    @WebMethod(action = "http://service.web.soap.dog.pets.com/findDogById")
    @WebResult(name = "findDogByIdOutputParam", targetNamespace = "http://service.web.soap.dog.pets.com/", partName = "findDogByIdResponseParam")
    public DogForm findDogById(
        @WebParam(name = "findDogByIdInputParam", targetNamespace = "http://service.web.soap.dog.pets.com/", partName = "findDogByIdRequestParam")
        int findDogByIdRequestParam);

}
