
package com.pets.dog.topdown.soap;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "dogFault", targetNamespace = "http://service.web.soap.dog.pets.com/")
public class SoapDogFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private DogFault faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public SoapDogFault(String message, DogFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public SoapDogFault(String message, DogFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.pets.dog.topdown.soap.DogFault
     */
    public DogFault getFaultInfo() {
        return faultInfo;
    }

}
