
package com.pets.dog.soap.web.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This method will help to load dog information
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DogSoapWebService", targetNamespace = "http://service.web.soap.dog.pets.com/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DogSoapWebService {


    /**
     * 
     * @param pdog
     * @return
     *     returns com.pets.dog.soap.web.service.StringResponse
     */
    @WebMethod(action = "http://service.web.soap.dog.pets.com/addDog")
    @WebResult(name = "stringResponse", targetNamespace = "http://service.web.soap.dog.pets.com/", partName = "rstring")
    public StringResponse addDog(
        @WebParam(name = "uploadDog", targetNamespace = "http://service.web.soap.dog.pets.com/", partName = "pdog")
        PDog pdog);

}
